### ISSUE TITLE
Not able to configure a mesh

### ISSUE THREAD

**Issue by bernhardrabe** [cloudalchemy/ansible-alertmanager#20]
Hello,

with this role it is not possible to configure a mesh.
To configure a mesh each peer needs to know it's peers. The [documentation](https://github.com/prometheus/alertmanager#high-availability) says:

> --mesh.peer value: initial peers (repeat flag for each additional peer)

so I need to be able to repeat the mesh.peer flag in the role var "alertmanager_cli_flags"

I tried

```
alertmanager_cli_flags:
  mesh.peer=123.456.789.1:6783
  mesh.peer=123.456.789.2:6783
```

but only the last "mesh.peer" is passed to the cli as parameter. I looked at the code and it seems that a dictionary/map is used which always overrides the the same key with another value. That's why only the last key is passed

A workaround I found is setting a default value and passing "more":
```
alertmanager_cli_flags:
  log.level: "info --mesh.peer=123.456.789.1:6783 --mesh.peer=123.456.789.2:6783"
```

**Comment by rdemachkovych** [comment]
It can be an issue with software version (python, ansible) or jinja template. I will try to catch it.

**Comment by paulfantom** [comment]
It's not an issue with software. Basically it comes down to 2 things:
1) design of alertmanager, which accepts multiple `mesh.peer` parameters on command line
2) defining `alertmanager_cli_flags` as dict, which in turn doesn't allow duplicate/multiple keys

I think we have two ways of fixing it:
1) change `alertmanager_cli_flags` to store a list of values
2) separate mesh configuration into another variable (ex. `alertmanager_mesh`) and concatenate it with `alertmanager_cli_flags` in service template.

For me second way is clearer and maybe will allow us better control, since we could write some preflight checks and notify user if he/she does sth wrong.

**Comment by bernhardrabe** [comment]
I totally agree with paul - this is a problem of the role.

I would also prefer the second way. Also this gives you more flexibility when the configuration of the mesh configuration changes (from the alert manager  side). Which most likely will, as it it `under active development` as described in the readme
